[FX-882] Document collectPinForDeferredCapture in README.md
teamforage/forage-ios-sdk pull request #142
Opened 2023-12-21 21:52 UTC by kimberleehowley

## What

Adding documentation for new method. 

## Why

Docs will help anybody reading the Readme to know how the function works. 

## Test Plan

- ✅ | Not a front-end change
- ✅ | Previewed Markdown in VSCode 

## How

- I'll close the PR if it breaks things, but this just edited the README.md

2023-12-22 13:19 UTC, dleis612 approved these changes

2024-01-02 16:41 UTC, djoksimo requested changes

2024-01-02 16:41 UTC, djoksimo commented on README.md
> +func collectPinForDeferredCapture(
```suggestion
func deferPaymentCapture(
```

2024-01-02 16:41 UTC, djoksimo commented on README.md
> +Call `ForageSDK.shared.collectPinForDeferredCapture` to collect a customer's EBT Card PIN before capturing a `Payment` server-side.
```suggestion
Call `ForageSDK.shared.deferPaymentCapture` to collect a customer's EBT Card PIN **before** capturing a `Payment` server-side.
```

2024-01-02 16:41 UTC, djoksimo commented on README.md
> +ForageSDK.shared.collectPinForDeferredCapture(
```suggestion
ForageSDK.shared.deferPaymentCapture(
```

2024-01-02 17:41 UTC, djoksimo approved these changes

2024-01-02 17:48 UTC, merged