[FX-933] Add support for single ForageError
teamforage/forage-ios-sdk pull request #147
Opened 2024-01-09 01:03 UTC by djoksimo

## What

- [x] Add support for `ForageError`
- [x] Update tests to cover both paths
- [x] Add more `ForageError` coverage in the sample app and log `ForageError` 
- [x] Updated README to document Forage error handling

## Why

https://linear.app/joinforage/issue/FX-933/ios-support-single-error-for-client-facing-errors

## Test Plan

- ✅ Updated unit tests
- ✅ Updated sample app
- ✅ Did some manual verification across edge cases like forage errors with `details` (ebt_error_51)

## How

Have to bump `MINOR` version level of the associated release.

2024-01-09 01:05 UTC, djoksimo commented on Sources/ForageSDK/Foundation/Network/Provider.swift
> +            )))
Updated to [more accurate/documented error code](https://docs.joinforage.app/reference/errors#invalid_input_data)

2024-01-10 15:42 UTC, dleis612 requested changes

2024-01-11 00:19 UTC, djoksimo commented on Sources/ForageSDK/Foundation/Network/Model/ForageErrorModel.swift
> +    /// A developer-facing message about the error, not to be displayed to customers.
Good catch! ccc8dda2c8e85f91d334627277dd1c8110706120

2024-01-11 00:19 UTC, djoksimo commented on Sources/ForageSDK/Foundation/Network/Model/ForageErrorModel.swift
> +    /// A short string explaining why the request failed. The error code string corresponds to the HTTP status code.
ccc8dda2c8e85f91d334627277dd1c8110706120

2024-01-11 12:16 UTC, dleis612 approved these changes

2024-01-11 14:54 UTC, merged