[FX-317] Part 2: Add log statements
teamforage/forage-ios-sdk pull request #55
Opened 2023-07-28 00:22 UTC by djoksimo

## What

## Why

## Test Plan

- ✅ | ❌ Not a front-end change
- ✅ | ❌ iOS QA Tests passed locally
- ✅ | ❌ Unit Tests passed locally

## How

2023-07-28 00:22 UTC, djoksimo commented
Current dependencies on/for this PR:
* main
  * **PR #54** <a href="https://app.graphite.dev/github/pr/teamforage/forage-ios-sdk/54" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #55** <a href="https://app.graphite.dev/github/pr/teamforage/forage-ios-sdk/55" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/teamforage/forage-ios-sdk/55?utm_source=stack-comment).

2023-07-28 13:17 UTC, dleis612 approved these changes

2023-07-31 13:44 UTC, devinmorgan requested changes
Thanks for adding all of these logs! I wanted to clarify whether this PR needs to be updated to take advantage of your most recent commits in #54? I noticed
1. references to `sharedLogger`
2. passing `error: nil` and `attributes: nil` (I thought these params were optional now)

2023-08-01 17:41 UTC, djoksimo commented
> 2\. passing `error: nil` and `attributes: nil` (I thought these params were optional now)

@devinmorgan it seems like this is easier said than done in swift when I set logger type to `ForageLogger` instead of `DatadogLogger`.

I will ask the Symphony team about this.

2023-08-03 21:43 UTC, devinmorgan commented
Sounds good! Happy to approve this though. It can be a follow up diff

2023-08-08 12:06 UTC, dleis612 approved these changes

2023-08-08 20:26 UTC, devinmorgan approved these changes
These latest changes include some great design decisions! Great work Danilo

2023-08-08 20:26 UTC, devinmorgan commented on Sources/ForageSDK/Foundation/Telemetry/ForageLogger.swift
> +    func addContext(_ newContext: ForageLogContext) -> ForageLogger
I love this pattern! Immutable and clean - nice work!!

2023-08-08 20:26 UTC, devinmorgan commented on Sources/ForageSDK/ForageSDK.swift
> +        self.service = LiveForageService(provider: provider, logger: logger)
love this! Instantiate a logger at the top level and pass as a dependency down to keep services pure. Great work!

2023-08-14 21:18 UTC, merged