[POP-69] (WIP) Enforce 80% code coverage for PRs
teamforage/forage-ios-sdk pull request #64
Opened 2023-08-07 21:37 UTC by nestorga

WIP. Need to do some live testing within GitHub, will update this once ready for review.

2023-08-08 14:30 UTC, devinmorgan approved these changes
Couldn't tell if this was still WIP or not so figure I give you approval just in case!

2023-08-08 16:02 UTC, nestorga commented on Gemfile
> +gem "xcov"
This is not implemented yet. Will ping you when it's ready for review

2023-08-08 16:04 UTC, nestorga commented
Good morning @devinmorgan,

Typically I use the PR draft state + comments to indicate if my PR is WIP or not:

![Screenshot 2023-08-08 at 9 03 20 AM](https://github.com/teamforage/forage-ios-sdk/assets/1429977/faa7bc56-8e5d-49c0-bd58-3ba74bf503b5)

Once ready for review, I'll move it from "Draft" to "Open" and ping you in the CR channel. Normally I'd wait to add reviewers, but it's enforced by `CODEOWNERS` in this repo.

2023-08-08 20:28 UTC, devinmorgan commented
> Normally I'd wait to add reviewers, but it's enforced by CODEOWNERS in this repo.

Ahhh OK yeah sounds like this is why I got pinged for the review. Cool beans - looking forward to what you ship next!

2023-08-08 22:32 UTC, nestorga commented on .github/workflows/Coverage.yaml
> +        run: gem install slather
Previously, I tried using a `Gemfile` and the [setup-ruby](https://github.com/ruby/setup-ruby) action. Unfortunately, this didn't modify the `PATH` as promised so I fell back to this comparatively simple approach.

2023-08-08 22:46 UTC, nestorga commented on .github/workflows/Coverage.yaml
> +        run: gem install slather
Previously, I tried using a `Gemfile` and the [setup-ruby](https://github.com/ruby/setup-ruby) action. Unfortunately, this didn't modify the `PATH` as promised so I fell back to this comparatively simple approach. 

I also tried `gem install slather -v 1.8.1`, but this seems to have caused all the dependencies to be built which adds several minutes to the build time, versus this which takes 5 seconds.

Given the difficulties above, I think using latest version here is the best option.

2023-08-08 22:47 UTC, nestorga commented on .github/workflows/Coverage.yaml
> +            -enableCodeCoverage YES
There was a [mysterious run ](https://github.com/teamforage/forage-ios-sdk/actions/runs/5802312850/job/15728454902)where this timed out after 10 minutes. Usually it takes around 5. Unsure if this is related to GH or the build itself. 

Something to keep an eye on.

2023-08-09 00:15 UTC, owenkim requested changes
I think it's worth thinking through the cost here before we hop into it.

2023-08-09 00:15 UTC, owenkim commented on .github/workflows/Coverage.yaml
> +    runs-on: macos-latest
This increases the cost by 10x compared to Linux. Are we sure we want to do this? Maybe just for every merge instead of every PR update?

2023-08-09 00:22 UTC, owenkim commented on .github/workflows/Coverage.yaml
> +    runs-on: macos-latest
Nevermind. https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions 

> GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners

2023-08-09 00:22 UTC, owenkim approved these changes

2023-08-09 20:50 UTC, merged